<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SrvSurvey.Core</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\docs\codexRef.json"
                      LogicalName="SrvSurvey.Core.Resources.codexRef.json" />
    <EmbeddedResource Include="..\..\SrvSurvey\allRuins.json"
                      LogicalName="SrvSurvey.Core.Resources.allRuins.json" />
    <EmbeddedResource Include="..\..\SrvSurvey\allStructures.json"
                      LogicalName="SrvSurvey.Core.Resources.allStructures.json" />
    <EmbeddedResource Include="..\..\SrvSurvey\allBeacons.json"
                      LogicalName="SrvSurvey.Core.Resources.allBeacons.json" />
    <EmbeddedResource Include="..\..\SrvSurvey\guardianSiteTemplates.json"
                      LogicalName="SrvSurvey.Core.Resources.guardianSiteTemplates.json" />
    <EmbeddedResource Include="..\..\data\guardian.zip"
                      LogicalName="SrvSurvey.Core.Resources.guardian.zip" />
    <EmbeddedResource Include="..\..\SrvSurvey\colonization-costs2.json"
                      LogicalName="SrvSurvey.Core.Resources.colonization-costs2.json" />
  </ItemGroup>

</Project>
