<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SrvSurvey.Core</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LuaCSharp" Version="0.5.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\ReferenceData\codexRef.json"
                      LogicalName="SrvSurvey.Core.Resources.codexRef.json" />
    <EmbeddedResource Include="Resources\ReferenceData\nebulae.json"
                      LogicalName="SrvSurvey.Core.Resources.nebulae.json" />
    <EmbeddedResource Include="Resources\ReferenceData\allRuins.json"
                      LogicalName="SrvSurvey.Core.Resources.allRuins.json" />
    <EmbeddedResource Include="Resources\ReferenceData\allStructures.json"
                      LogicalName="SrvSurvey.Core.Resources.allStructures.json" />
    <EmbeddedResource Include="Resources\ReferenceData\allBeacons.json"
                      LogicalName="SrvSurvey.Core.Resources.allBeacons.json" />
    <EmbeddedResource Include="Resources\ReferenceData\guardianSiteTemplates.json"
                      LogicalName="SrvSurvey.Core.Resources.guardianSiteTemplates.json" />
    <EmbeddedResource Include="Resources\ReferenceData\humanSiteTemplates.json"
                      LogicalName="SrvSurvey.Core.Resources.humanSiteTemplates.json" />
    <EmbeddedResource Include="Resources\ReferenceData\guardian.zip"
                      LogicalName="SrvSurvey.Core.Resources.guardian.zip" />
    <EmbeddedResource Include="Resources\ReferenceData\colonization-costs2.json"
                      LogicalName="SrvSurvey.Core.Resources.colonization-costs2.json" />
    <EmbeddedResource Include="Resources\ReferenceData\ggg.json"
    <EmbeddedResource Include="Resources\ReferenceData\well-known-uris.json"
                      LogicalName="SrvSurvey.Core.Resources.well-known-uris.json" />
                      LogicalName="SrvSurvey.Core.Resources.ggg.json" />
    <EmbeddedResource Include="Resources\bio-criteria\*.json"
                      LogicalName="SrvSurvey.Core.Resources.bio-criteria.%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
