namespace SrvSurvey.Desktop.ViewModels;

public sealed partial class MainWindowViewModel
{
    private JournalProjection CreateJournalProjection() =>
        new(
            new DesktopJournalProjectionAdapter(
                new JournalProjectionDependencies
                {
                    State = projectionState,
                    IsDiagnosticReplay = () => IsDiagnosticReplay,
                    FrontierProfile = FrontierProfile,
                    OverlayExceptions = OverlayExceptions,
                    DesktopBehavior = DesktopBehavior,
                    OverlayBehavior = OverlayBehavior,
                    ScreenshotProcessing = ScreenshotProcessing,
                    DockToDock = DockToDock,
                    Notifications = Notifications,
                    PulseOverlay = PulseOverlay,
                    GalaxyMap = GalaxyMap,
                    NetworkPrivacy = NetworkPrivacy,
                    VoxStellar = VoxStellar,
                    Inara = Inara,
                    Edsm = Edsm,
                    QuestWorkspace = QuestWorkspace,
                    CommanderInstances = CommanderInstances,
                    GroundTarget = GroundTarget,
                    SystemNotes = SystemNotes,
                    Journey = Journey,
                    Route = Route,
                    RouteManager = RouteManager,
                    FleetCarrierRoute = FleetCarrierRoute,
                    FleetCarrierRouteManager = FleetCarrierRouteManager,
                    JumpInfo = JumpInfo,
                    StationInfo = StationInfo,
                    HumanSite = HumanSite,
                    SystemSurvey = SystemSurvey,
                    SurfaceSurvey = SurfaceSurvey,
                    Mining = Mining,
                    MineMap = MineMap,
                    MiningWorkspace = MiningWorkspace,
                    Firegroups = Firegroups,
                    Combat = Combat,
                    BiologyCodex = BiologyCodex,
                    CodexBingo = CodexBingo,
                    Search = Search,
                    BoxelSearch = BoxelSearch,
                    NearestSystems = NearestSystems,
                    Guardian = Guardian,
                    Colonization = Colonization,
                    JournalInspector = JournalInspector,
                    JournalPostProcessor = JournalPostProcessor,
                    companionTimelineStore = companionTimelineStore,
                    applicationLogService = applicationLogService,
                    firstFootfallInferenceCancellation = firstFootfallInferenceCancellation,
                    routeAutoCopyCoordinator = routeAutoCopyCoordinator,
                    boxelSurveyStats = boxelSurveyStats,
                    greenGasGiantPublicationCoordinator = greenGasGiantPublicationCoordinator,
                    commanderCodexJournalTracker = commanderCodexJournalTracker,
                    eddnPublisher = eddnPublisher,
                    voxStellarPublisher = voxStellarPublisher,
                    inaraPublisher = inaraPublisher,
                    edsmPublisher = edsmPublisher,
                    questSettingsStore = questSettingsStore,
                    questRuntimeCoordinator = questRuntimeCoordinator,
                    folderResolution = folderResolution,
                    Shell = new JournalProjectionShell
                    {
                        EnsureCommanderProfileAsync = EnsureCommanderProfileAsync,
                        UpdateSystemBodyDataGameSessionConfirmation = UpdateSystemBodyDataGameSessionConfirmation,
                        UpdateActiveSystemVisit = UpdateActiveSystemVisit,
                        LoadCurrentSystemHistoryAsync = LoadCurrentSystemHistoryAsync,
                        LoadCurrentSystemBodyDataAsync = LoadCurrentSystemBodyDataAsync,
                        PersistSystemScanAsync = PersistSystemScanAsync,
                        RefreshSystemSurveyCommanderCodexAsync = RefreshSystemSurveyCommanderCodexAsync,
                        ApplyFirstFootfallTextCommandsAsync = ApplyFirstFootfallTextCommandsAsync,
                        TryInferFirstFootfallAsync = TryInferFirstFootfallAsync,
                        ApplyDesktopTextCommandsAsync = ApplyDesktopTextCommandsAsync,
                        SaveExplorationAsync = SaveExplorationAsync,
                        SaveExobiologyAsync = SaveExobiologyAsync,
                        UpdateExplorationDisplay = UpdateExplorationDisplay,
                        UpdateExobiologyDisplay = UpdateExobiologyDisplay,
                        ApplyMonitorStatusMessages = ApplyMonitorStatusMessages,
                        UpdateQuestOverlayPresentation = UpdateQuestOverlayPresentation,
                        StartSystemBodyDataRetryIfDue = StartSystemBodyDataRetryIfDue,
                        CommanderCodexStatus = message => CommanderCodexStatusMessage = message,
                        QuestStatus = message => QuestStatusMessage = message,
                        PendingBodyData = task => PendingSystemBodyDataLoad = task,
                        RequestShutdown = () => journalCommandShutdownRequester?.Invoke() ?? Task.CompletedTask,
                    },
                }
            )
        );
}
