using Avalonia;
using Avalonia.Controls;
using Avalonia.Media;

namespace SrvSurvey.Desktop.Controls;

/// <summary>
/// Reproduces the background generated by the legacy WinForms plotters: a
/// black field with a subtle three-pixel scan-line tile and orange edge bands.
/// </summary>
public sealed class LegacyOverlayBackgroundControl : Control
{
    public static readonly StyledProperty<IBrush?> BackgroundBrushProperty =
        AvaloniaProperty.Register<LegacyOverlayBackgroundControl, IBrush?>(
            nameof(BackgroundBrush));

    public static readonly StyledProperty<IBrush?> StripeBrushProperty =
        AvaloniaProperty.Register<LegacyOverlayBackgroundControl, IBrush?>(
            nameof(StripeBrush));

    public static readonly StyledProperty<IBrush?> EdgeBrushProperty =
        AvaloniaProperty.Register<LegacyOverlayBackgroundControl, IBrush?>(
            nameof(EdgeBrush));

    public static readonly StyledProperty<IBrush?> EdgeDimBrushProperty =
        AvaloniaProperty.Register<LegacyOverlayBackgroundControl, IBrush?>(
            nameof(EdgeDimBrush));

    static LegacyOverlayBackgroundControl()
    {
        AffectsRender<LegacyOverlayBackgroundControl>(
            BackgroundBrushProperty,
            StripeBrushProperty,
            EdgeBrushProperty,
            EdgeDimBrushProperty);
    }

    public IBrush? BackgroundBrush
    {
        get => GetValue(BackgroundBrushProperty);
        set => SetValue(BackgroundBrushProperty, value);
    }

    public IBrush? StripeBrush
    {
        get => GetValue(StripeBrushProperty);
        set => SetValue(StripeBrushProperty, value);
    }

    public IBrush? EdgeBrush
    {
        get => GetValue(EdgeBrushProperty);
        set => SetValue(EdgeBrushProperty, value);
    }

    public IBrush? EdgeDimBrush
    {
        get => GetValue(EdgeDimBrushProperty);
        set => SetValue(EdgeDimBrushProperty, value);
    }

    public override void Render(DrawingContext context)
    {
        base.Render(context);
        var bounds = new Rect(Bounds.Size);
        context.DrawRectangle(BackgroundBrush ?? Brushes.Black, null, bounds);

        var stripePen = new Pen(
            StripeBrush ?? new SolidColorBrush(Color.FromRgb(12, 12, 12)),
            1);
        for (var y = 0.5; y < bounds.Height; y += 3)
        {
            context.DrawLine(stripePen, new Point(0, y), new Point(bounds.Width, y));
        }

        if (bounds.Height < 8)
        {
            return;
        }

        var edge = new Pen(EdgeBrush ?? Brushes.Orange, 1);
        var edgeDim = new Pen(EdgeDimBrush ?? Brushes.DarkOrange, 1);
        DrawBand(context, bounds.Width, 3.5, edgeDim, edge, edgeDim);
        DrawBand(
            context,
            bounds.Width,
            bounds.Height - 5.5,
            edgeDim,
            edge,
            edgeDim);
    }

    private static void DrawBand(
        DrawingContext context,
        double width,
        double y,
        Pen first,
        Pen second,
        Pen third)
    {
        context.DrawLine(first, new Point(0, y), new Point(width, y));
        context.DrawLine(second, new Point(0, y + 1), new Point(width, y + 1));
        context.DrawLine(third, new Point(0, y + 2), new Point(width, y + 2));
    }
}
